"""
Milestone 12, Section 4.3: verifies demo-data's five data_retention_policy.*
fixtures (DOCX, PPTX, Markdown, Python, PNG/OCR) through the real ingestion
pipeline -- no database shortcuts, no mocks of extraction, classification,
chunking, embedding, indexing, or concept-linking.

Covers this milestone's stated verification requirements:
  - every one of the five fixtures reaches READY through the real
    /api/v1/documents upload + poll cycle,
  - they dedupe (via LocalConceptLinker's filename-fallback +
    concept_graph.resolve_concept's exact-name-match, both Milestone 7
    mechanisms, unmodified) into one concept with evidence from all five
    source types,
  - Search demonstrates cross-format retrieval: SearchIntent().handle(),
    called directly against the real (test) vector repository -- no fake
    VectorRepository, no monkeypatching of retrieval -- returns citations
    whose filenames span multiple of the five formats.

Uses the real fixture files checked into demo-data/, generated by
generate_demo_fixtures.py -- this test fails loudly (skips with a clear
reason) if that generator hasn't been run, rather than silently
fabricating substitute content that wouldn't actually exercise OCR/DOCX/
PPTX extraction.
"""

from pathlib import Path

import pytest

from app.db.session import SessionLocal
from app.models.concept import Concept
from app.schemas.intents import IntentRequest
from app.services.intents.search import SearchIntent

DEMO_DATA_DIR = Path(__file__).resolve().parents[3] / "demo-data"

FIXTURE_FILES = [
    ("data_retention_policy.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    (
        "data_retention_policy.pptx",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ),
    ("data_retention_policy.md", "text/markdown"),
    ("data_retention_policy.py", "text/x-python"),
    ("data_retention_policy.png", "image/png"),
]

pytestmark = pytest.mark.skipif(
    not all((DEMO_DATA_DIR / name).exists() for name, _ in FIXTURE_FILES),
    reason=(
        "demo-data/data_retention_policy.* fixtures not present -- run "
        "`python3 demo-data/generate_demo_fixtures.py` first."
    ),
)


def _upload_all_fixtures(client):
    document_ids = []
    for filename, mime in FIXTURE_FILES:
        path = DEMO_DATA_DIR / filename
        with open(path, "rb") as f:
            resp = client.post("/api/v1/documents", files={"file": (filename, f, mime)})
        assert resp.status_code == 201, f"{filename}: {resp.text}"
        document_ids.append((filename, resp.json()["id"]))
    return document_ids


def test_every_fixture_format_reaches_ready(registered_client):
    client, _ = registered_client
    document_ids = _upload_all_fixtures(client)

    for filename, document_id in document_ids:
        detail = client.get(f"/api/v1/documents/{document_id}").json()
        assert (
            detail["document"]["status"] == "READY"
        ), f"{filename} did not reach READY: {detail['document']}"


def test_five_formats_dedup_to_one_concept_with_cross_format_evidence(registered_client):
    """The core Milestone 12 Section 4.3 demonstration: five different
    source types, one filename stem, one concept, evidence spanning every
    format -- via the unmodified Milestone 7 dedup mechanism."""
    client, _ = registered_client
    document_ids = _upload_all_fixtures(client)

    concept_ids = set()
    for filename, document_id in document_ids:
        detail = client.get(f"/api/v1/documents/{document_id}").json()
        concepts = detail["concepts"]
        assert len(concepts) == 1, f"{filename}: expected exactly one concept link, got {concepts}"
        concept_ids.add(concepts[0]["conceptId"])

    assert len(concept_ids) == 1, f"expected all five fixtures to resolve to one concept, got {concept_ids}"
    concept_id = concept_ids.pop()

    detail = client.get(f"/api/v1/concepts/{concept_id}").json()
    assert detail["concept"]["name"] == "Data Retention Policy"
    evidence_filenames = {e["filename"] for e in detail["evidence"]}
    assert evidence_filenames == {name for name, _ in FIXTURE_FILES}

    evidence_extensions = {Path(f).suffix for f in evidence_filenames}
    assert evidence_extensions == {".docx", ".pptx", ".md", ".py", ".png"}, (
        "expected evidence from all five distinct source types, got extensions " f"{evidence_extensions}"
    )

    db = SessionLocal()
    try:
        concept = db.get(Concept, concept_id)
        assert concept is not None
        assert concept.normalized_name == "data retention policy"
    finally:
        db.close()


def test_search_demonstrates_cross_format_retrieval(registered_client):
    """Search/Explain cross-format retrieval requirement: a real question
    against the real (test) vector repository returns citations spanning
    multiple of the five ingested formats -- SearchIntent is called
    directly (same pattern as tests/test_search_intent.py), but with no
    fakes/mocks here, since the point is to prove real retrieval works
    across formats, not to unit-test SearchIntent's branching logic."""
    client, _ = registered_client
    _upload_all_fixtures(client)

    workspace_id = client.get("/api/v1/workspace").json()["workspace"]["id"]

    db = SessionLocal()
    try:
        from app.models.workspace import Workspace

        workspace = db.get(Workspace, workspace_id)
        assert workspace is not None

        response = SearchIntent().handle(
            db, workspace, IntentRequest(intent="SEARCH", question="How long are financial records retained?")
        )

        assert response.status == "OK"
        assert response.result.hits, "expected at least one search hit"
        hit_filenames = {hit.documentFilename for hit in response.result.hits}
        hit_extensions = {Path(f).suffix for f in hit_filenames}
        assert len(hit_extensions) > 1, (
            f"expected search results to span multiple formats, got only {hit_extensions} "
            f"from filenames {hit_filenames}"
        )
    finally:
        db.close()
